---
- name: Insall Homebrew + Python 3
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_installed_packages:
      - python@3
# This is overwritten by our group_vars (cpp.build-machines)
