---
- name: Install system python (Centos)
  yum:
    name:
      - python27
      - python36
      - python36-pip
    state: latest
    use_backend: yum
  when: "ansible_os_family == 'RedHat'"

- name: Install system python (Debian)
  apt:
    name:
      - python-pip
      - python3-pip
    state: latest
  when: "ansible_os_family == 'Debian'"

- name: Install python (MacOS)
  homebrew:
    name:
        - python@3
        - python@2
  when: "ansible_os_family == 'Darwin'"

- name: Install python (Windows)
  win_chocolatey:
    name:
      - python2
      - python
    state: present
  when: "ansible_os_family == 'Windows'"

- name: Update facts to get new default Python interpreter
  setup:
    filter: "discovered_interpreter_python"

- name: Display default Python interpreter
  debug:
    var: "ansible_facts['ansible_python']"
  when: "ansible_os_family == 'Windows'"

- name: Set default Windows Python interpreter
  set_fact:
    ansible_python_interpreter: c:\Python37\python.exe
